name: Maven Central Repo Deployment
# 当 release 的时候触发
#on:
#  release:
#    types: [released]
on:
  push:
    branches: [ release ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2
      - name: Set up Maven Central Repo
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: sonatype-nexus-staging
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Publish to Maven Central Repo
        uses: samuelmeuli/action-maven-publish@v1
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_SECRET_KEY: ${{ secrets.GPG_PUB }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
        with:
          gpg_private_key: GPG_SECRET_KEY
          gpg_passphrase: GPG_PASSPHRASE
          nexus_username: MAVEN_USERNAME
          nexus_password: MAVEN_PASSWORD

